// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuz4_xyYOsQVtw7t2ksubVhFirR5_Mxk',
    appId: '1:382251378395:web:17e7a121442c06ba0b4efe',
    messagingSenderId: '382251378395',
    projectId: 'notesapptutorialyt',
    authDomain: 'notesapptutorialyt.firebaseapp.com',
    storageBucket: 'notesapptutorialyt.appspot.com',
    measurementId: 'G-6FKRS961PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwyy-ujwr0AxO2kj7plfHASoIAmX640i0',
    appId: '1:382251378395:android:966b11db7576dbab0b4efe',
    messagingSenderId: '382251378395',
    projectId: 'notesapptutorialyt',
    storageBucket: 'notesapptutorialyt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8z-qBnep35J5tDcbD9hw1TlRyDQxstt8',
    appId: '1:382251378395:ios:a4ee6ca4247d5c5b0b4efe',
    messagingSenderId: '382251378395',
    projectId: 'notesapptutorialyt',
    storageBucket: 'notesapptutorialyt.appspot.com',
    iosBundleId: 'com.KennethSoftware.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8z-qBnep35J5tDcbD9hw1TlRyDQxstt8',
    appId: '1:382251378395:ios:a4ee6ca4247d5c5b0b4efe',
    messagingSenderId: '382251378395',
    projectId: 'notesapptutorialyt',
    storageBucket: 'notesapptutorialyt.appspot.com',
    iosBundleId: 'com.KennethSoftware.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUuz4_xyYOsQVtw7t2ksubVhFirR5_Mxk',
    appId: '1:382251378395:web:6df8fd603624c70f0b4efe',
    messagingSenderId: '382251378395',
    projectId: 'notesapptutorialyt',
    authDomain: 'notesapptutorialyt.firebaseapp.com',
    storageBucket: 'notesapptutorialyt.appspot.com',
    measurementId: 'G-XQNKGH769Z',
  );
}
